name: Test Workflow

on: push 

jobs:
 test:
   runs-on: ubuntu-latest
   
   services:
    image: postgres
    env:
    - POSTGRES_USER: postgres
    - POSTGRES_PASSWORD: postgres
    - POSTGRES_BD: dgen_db
    ports:
    - 5432:5432
    options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
   
   steps:
   - name: Checkout source code
     uses: actions/checkout@v2
   
   - name: Set up Python 3.8.9
     uses: actions/setup-python@v2

   - name: Install dependencies
     run: pip install -r requirements.txt
   
   - name: Run tests
     run: python dgen_model.py test